### ISSUE TITLE
UBSAN issue in 'ares-test-live.cc'

### ISSUE THREAD

**Issue by gvanem** [c-ares/c-ares#648]
Building using clang-cl (ver. 17) on Windows and with [UBSAN](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) (*"Undefined Behaviour Sanitation"*), triggers this
run-time error in `ares-test.exe`
```
src/lib/ares__socket.c:385:12: runtime error: call to function ares::test::DefaultChannelTest_VerifySocketFunctionCallback_Test::TestBody::
<lambda_0>::__invoke through pointer to incorrect function type 'unsigned long long (*)(int, int, int, void *)'
F:\MinGW32\src\inet\DNS\c-ares\test\ares-test-live.cc:736: note: ares::test::DefaultChannelTest_VerifySocketFunctionCallback_Test::TestBody:
:<lambda_0>::__invoke defined here
    #0 0x7fff70a372b3 in ares__open_socket F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares__socket.c:385
    #1 0x7fff70a3539a in ares__open_connection F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares__socket.c:276
    #2 0x7fff70a7f9e2 in ares__send_query F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares_process.c:963
    #3 0x7fff70a8d7cd in ares_send_ex F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares_send.c:146
    #4 0x7fff70a877cb in ares_query_qid F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares_query.c:82
    #5 0x7fff70a5bb1a in next_dns_lookup F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares_getaddrinfo.c:739
    #6 0x7fff70a5bb1a in next_lookup F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares_getaddrinfo.c:437
    #7 0x7fff70a5bdae in next_lookup F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares_getaddrinfo.c:441
    #8 0x7fff70a595a2 in ares_getaddrinfo_int F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares_getaddrinfo.c:619
    #9 0x7fff70a595a2 in ares_getaddrinfo F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares_getaddrinfo.c:680
    #10 0x7fff70a60e01 in ares_gethostbyname F:\MinGW32\src\inet\DNS\c-ares\src\lib\ares_gethostbyname.c:125
    #11 0x7ff6b1864949 in ares::test::DefaultChannelTest_VerifySocketFunctionCallback_Test::TestBody(void) F:\MinGW32\src\inet\DNS\c-ares\test\ares-test-live.cc:747
    #12 0x7fff78716d7a in testing::internal::HandleSehExceptionsInMethodIfSupported<class testing::Test, void>(
class testing::Test *, void (__cdecl testing::Test::*)(void), char const *) F:\MinGW32\src\inet\GoogleCode\gtest\googletest\src\gtest.cc:2606
    #13 0x7fff78716bf5 in testing::internal::HandleExceptionsInMethodIfSupported<class testing::Test, void>(
class testing::Test *, void (__cdecl testing::Test::*)(void), char const *) F:\MinGW32\src\inet\GoogleCode\gtest\googletest\src\gtest.cc:2649
    #14 0x7fff78759210 in testing::Test::Run(void) F:\MinGW32\src\inet\GoogleCode\gtest\googletest\src\gtest.cc:2688
    #15 0x7fff7875938e in testing::TestInfo::Run(void) F:\MinGW32\src\inet\GoogleCode\gtest\googletest\src\gtest.cc:2837
    #16 0x7fff787596dd in testing::TestSuite::Run(void) F:\MinGW32\src\inet\GoogleCode\gtest\googletest\src\gtest.cc:3016
    #17 0x7fff7875a002 in testing::internal::UnitTestImpl::RunAllTests(void) F:\MinGW32\src\inet\GoogleCode\gtest\googletest\src\gtest.cc:5922
    #18 0x7fff78716dda in testing::internal::HandleSehExceptionsInMethodIfSupported<class testing::internal::UnitTestImpl, bool>(
class testing::internal::UnitTestImpl *, bool (__cdecl testing::internal::UnitTestImpl::*)(void), char const *) F:\MinGW32\src\inet\GoogleCode\gtest\googletest\src\gtest.cc:2606
    #19 0x7fff78716d45 in testing::internal::HandleExceptionsInMethodIfSupported<class testing::internal::UnitTestImpl, bool>(
class testing::internal::UnitTestImpl *, bool (__cdecl testing::internal::UnitTestImpl::*)(void), char const *) F:\MinGW32\src\inet\GoogleCode\gtest\googletest\src\gtest.cc:2649
    #20 0x7fff787599a9 in testing::UnitTest::Run(void) F:\MinGW32\src\inet\GoogleCode\gtest\googletest\src\gtest.cc:5486
    #21 0x7ff6b162192e in RUN_ALL_TESTS f:\MinGW32\src\inet\GoogleCode\gtest\googletest\include\gtest\gtest.h:2316
    #22 0x7ff6b162192e in main F:\MinGW32\src\inet\DNS\c-ares\test\ares-test-main.cc:53
```

The program continues. But I fail to understand what wrong with this lambda:
```c
  my_functions.asocket = [](int af, int type, int protocol, void * p) {
    EXPECT_NE(nullptr, p);
    (*reinterpret_cast<size_t *>(p))++;
    return ::socket(af, type, protocol);
  };
```

Some (false positive) related to `int` vs. `SOCKET`?

**Comment by gvanem** [comment]
Trying this (w/o really knowing lambdas), there's no runtime error:
```diff
--- a/test/ares-test-live.cc 2023-12-07 07:33:04
+++ b/test/ares-test-live.cc 2023-12-07 10:01:41
@@ -733,7 +733,7 @@
   auto my_functions = VirtualizeIO::default_functions;
   size_t count = 0;

-  my_functions.asocket = [](int af, int type, int protocol, void * p) {
+  my_functions.asocket = [](int af, int type, int protocol, void * p) -> ares_socket_t {
     EXPECT_NE(nullptr, p);
     (*reinterpret_cast<size_t *>(p))++;
     return ::socket(af, type, protocol);
```

**Comment by bradh352** [comment]
Yeah, its gotta be due to windows SOCKET vs int.  Your fix looks sane to me if you want to commit it or submit a PR.

I guess we should add some AppVeyor ASAN / UBSAN tests, can probably model it off of the MSYS2 test we have in there now as the easiest way to get access to clang.  We should probably also consider running the scan build static analysis.

That said, AppVeyor has gotten super slow these days.

**Comment by bradh352** [comment]
I've incorporated your patch into #649

**Comment by bradh352** [comment]
Well, ASAN isn't building and I have no idea what it means.  I'm assuming its something we can't control:
```
error: cannot make section .ASAN$GL associative with sectionless symbol _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE4nposE
1 error generated.
```

Trying just UBSAN now...

**Comment by bradh352** [comment]
neither scan-build nor ASAN appear to work, UBSAN does though so I enabled that.
